import asyncio
from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from datetime import datetime
import time

from config import CONFIG
from sensors import SensorManager
from leds import LEDManager
from weather import WeatherManager
from system import SystemManager
from pydantic import BaseModel

app = FastAPI()

# Enable CORS for development (allowing Vite frontend to talk to us)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize Modules
sensors_mgr = SensorManager()
leds_mgr = LEDManager()
weather_mgr = WeatherManager()

class SettingsUpdate(BaseModel):
    ntp_server: str = None
    location_auto: bool = None
    threshold_warning: float = None
    threshold_critical: float = None
    sensor_id: str = None # If provided, thresholds apply to this sensor. If "global" or None, applies globally.
    sensor_name: str = None # Optional name update for sensor_id
    mock_mode: bool = None
    led_brightness: int = None

# ... (startup event and background tasks unchanged) ...

# ...

@app.post("/api/settings")
def update_settings(settings: SettingsUpdate):
    try:
        current = CONFIG.get_all()
        # Log payload
        try:
            with open("backend_debug.log", "a") as f:
                f.write(f"SETTINGS REQUEST: {settings}\n")
        except: pass

        # Check structure update (migration fix if config.json was old)
        if "global" not in current["temp_thresholds"]:
             current["temp_thresholds"] = {
                 "global": current["temp_thresholds"],
                 "sensors": {}
             }

        # Update Thresholds
        target_scope = "global"
        if settings.sensor_id and settings.sensor_id != "global":
            target_scope = "sensors"
            
        if target_scope == "global":
            if settings.threshold_warning is not None:
                current["temp_thresholds"]["global"]["warning"] = settings.threshold_warning
            if settings.threshold_critical is not None:
                 current["temp_thresholds"]["global"]["critical"] = settings.threshold_critical
        else:
            # Per-sensor
            sid = settings.sensor_id
            if sid not in current["temp_thresholds"]["sensors"]:
                # Copy global as baseline if creating new
                 current["temp_thresholds"]["sensors"][sid] = \
                     current["temp_thresholds"]["global"].copy()
            
            if settings.threshold_warning is not None:
                current["temp_thresholds"]["sensors"][sid]["warning"] = settings.threshold_warning
            if settings.threshold_critical is not None:
                 current["temp_thresholds"]["sensors"][sid]["critical"] = settings.threshold_critical
            
            # Update Name
            if settings.sensor_name is not None:
                 if "sensor_names" not in current:
                     current["sensor_names"] = {}
                 current["sensor_names"][sid] = settings.sensor_name

        # Update Location
        if settings.location_auto is not None:
            current["location"]["auto"] = settings.location_auto
            
        # Update Mock Mode
        if settings.mock_mode is not None:
            current["mock_mode"] = settings.mock_mode
            
        # Update LED Brightness
        if settings.led_brightness is not None:
            current["led_brightness"] = settings.led_brightness
            
        CONFIG.save()
        return {"status": "ok", "config": current}
        
    except Exception as e:
        try:
            with open("backend_debug.log", "a") as f:
                f.write(f"SETTINGS ENDPOINT ERROR: {e}\n")
        except: pass
        raise HTTPException(status_code=500, detail=str(e))
    
    # Reload Managers
    sensors_mgr.reload_config()
    leds_mgr.reload_config()
    
    # Update NTP
    msg = "Settings updated"
    if settings.ntp_server:
        success, ntp_msg = SystemManager.set_ntp_server(settings.ntp_server)
        msg += f". {ntp_msg}"
        
    return {"message": msg, "config": CONFIG.get_all()}

# Mount Frontend Static Files (Production Mode)
# This serves the 'dist' folder generated by 'npm run build'
import os
frontend_dist = os.path.join(os.path.dirname(__file__), "..", "frontend", "dist")
if os.path.exists(frontend_dist):
    app.mount("/", StaticFiles(directory=frontend_dist, html=True), name="static")
else:
    print(f"WARNING: Frontend dist not found at {frontend_dist}. Run 'npm run build' in frontend/")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
